# Generated by Django 3.1.13 on 2022-01-10 07:37

from django.db import migrations, models

from common.utils.timezone import as_current_tz


def fill_ticket_serial_number(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    tickets = Ticket.objects.all().order_by('date_created')

    today = '00000000'
    today_num = 1
    to_update = []

    print(f'\nFill ticket serial number ... ', end='')
    for ticket in tickets:
        # 跑这个脚本的时候，所有 ticket.serial_num == null
        date_created = as_current_tz(ticket.date_created)
        date_str = date_created.strftime('%Y%m%d')
        if date_str != today:
            today = date_str
            today_num = 1

        ticket.serial_num = today + '%04d' % today_num
        to_update.append(ticket)
        today_num += 1

    Ticket.objects.bulk_update(to_update, fields=('serial_num',))
    print(len(to_update), end='')


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticketsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='serial_num',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Serial number'),
        ),
        migrations.RunPython(fill_ticket_serial_number),
    ]
